version: 2.1

jobs:
  ubuntu1804-python2:
    docker:
      - image: stbtester/circleci:ubuntu1804-python2
    environment:
      python_version: 2.7
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  ubuntu1804-python3:
    docker:
      - image: stbtester/circleci:ubuntu1804-python3
    environment:
      python_version: 3
      LANG: en_GB.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - pylint
      - pytest
      - integrationtests

  python-package:
    docker:
      - image: circleci/python:3.6.9
    environment:
      python_version: 3
      LANG: C.UTF-8
      SHELL: /bin/bash
      TERM: xterm
      enable_virtual_stb: no
    steps:
      - checkout
      - check-pythonpackage

commands:
  pylint:
    steps:
      - run:
          name: make check-pylint
          command: |
            tesseract --version
            make check-pylint
  pytest:
    steps:
      - run: make check-pytest
  integrationtests:
    steps:
      - run: make check-integrationtests
  check-pythonpackage:
    steps:
      - run: python3 setup.py sdist
      - run:
          name: install & test
          command: |
            rm -rf stbt _stbt &&
            python3 -m venv build_env &&
            source build_env/bin/activate &&
            pip3 install pytest==3.3.2 attrs==17.4.0 \
                         pylint==2.4.4 astroid==2.3.3 &&
            pip3 install dist/*.tar.gz &&
            make check-pythonpackage PYTEST=pytest

workflows:
  test_all:
    jobs:
      - python-package
      - ubuntu1804-python2
      - ubuntu1804-python3
